# Generated by Django 3.1.5 on 2024-05-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_auto_20240507_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='video',
        ),
    ]
