# Generated by Django 3.1.5 on 2024-05-08 07:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0006_remove_answer_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='complaint',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
        migrations.AlterField(
            model_name='answer',
            name='respondent',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answe_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
