# Generated by Django 3.1.5 on 2024-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_question_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
