# Generated by Django 3.1.5 on 2024-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_complaint_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
