# Generated by Django 3.1.5 on 2024-06-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='is_indemnity_payer',
            field=models.BooleanField(default=False),
        ),
    ]
