# Generated by Django 3.1.5 on 2024-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0008_systemuser_is_indemnity_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='thumbnailUrl',
            field=models.ImageField(blank=True, null=True, upload_to='upload_thumbnail/'),
        ),
    ]
