# Generated by Django 3.1.5 on 2024-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0009_chatgroup_thumbnailurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
