# Generated by Django 3.1.5 on 2024-06-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0010_chatgroup_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='file',
        ),
    ]
