# Generated by Django 3.1.5 on 2024-06-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0013_shapefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapefile',
            old_name='file',
            new_name='shp_file',
        ),
    ]
